# -*- coding: utf-8 -*-
"""fineuned llama for rizz

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MRmMjloLRVc3iau7eRxqb6BvApgS8Qtp
"""

with open('output.json', 'r') as f:
    loaded_data = json.load(f)
print("Data successfully loaded from 'output.json'")

print("First 5 elements of the loaded data:")
for i, item in enumerate(loaded_data[:5]):
    print(f"  {i+1}. {item}")

data

import json


def transform_to_dynamic_llama(data):
    mappings = {
        "universal": ("Poetry", "Sincerity"),
        "old_school_romantic": ("Aviation", "Nostalgia"),
        "confident": ("Fine Dining", "Boldness"),
        "genuine": ("Real Talk", "Simplicity"),
        "romantic": ("Theme Parks", "Happiness"),
        "playful": ("Social Situations", "Humor"),
        "clever": ("Modern Trends", "Witty References"),
        "bold": ("Confidence", "Directness"),
        "direct": ("Raw Honesty", "Clarity"),
        "ted_mosby": ("Destiny", "Life Stories"),
        "jim_halpert": ("Workplace Life", "Disarming Honesty"),
        "shakespeare": ("Classical Literature", "Eternal Devotion"),
        "joey_tribbiani": ("Casual Connection", "Charm"),
        "chandler_bing": ("Self-Deprecation", "Vulnerable Humor"),
        "ross_geller": ("Science/History", "Academic Interest"),
        "leonard_hofstadter": ("Physics", "Alternative Realities"),
        "sheldon_cooper": ("Logic", "Analytical Proof"),
        "raj_koothrappali": ("Cinema", "Romantic Gestures"),
        "howard_wolowitz": ("Engineering", "Technical Precision"),
        "phil_dunphy": ("Real Estate", "Optimism"),
        "claire_dunphy": ("Organization", "Spontaneity"),
        "gloria_delgado": ("Heritage", "Fierce Intensity"),
        "jay_pritchett": ("Experience", "Straight Talk"),
        "cameron_tucker": ("The Arts", "Theatricality")
    }

    formatted_rows = []
    for entry in data:
        char = entry.get("character_energy", "universal")
        x, y = mappings.get(char, ("Life", "Honesty"))

        row = {
            "instruction": "Generate a high-conviction romantic line for a person with specific interests.",
            "input": f"Target: Into [X: {x}] and loves [Y: {y}].",
            "output": entry["line"]
        }
        formatted_rows.append(row)
    return formatted_rows

import json

# Load the data from 'output.json'
with open('data.json', 'r') as f:
    data_from_json = json.load(f)

# Transform the loaded data
result = transform_to_dynamic_llama(data_from_json)

with open('llama_train_final.jsonl', 'w') as f:
    for r in result:
        f.write(json.dumps(r) + '\n')

pip install unsloth

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# import os, re
# if "COLAB_" not in "".join(os.environ.keys()):
#     !pip install unsloth
# else:
#     # Do this only in Colab notebooks! Otherwise use pip install unsloth
#     import torch; v = re.match(r"[0-9]{1,}\.[0-9]{1,}", str(torch.__version__)).group(0)
#     xformers = "xformers==" + ("0.0.33.post1" if v=="2.9" else "0.0.32.post2" if v=="2.8" else "0.0.29.post3")
#     !pip install --no-deps bitsandbytes accelerate {xformers} peft trl triton cut_cross_entropy unsloth_zoo
#     !pip install sentencepiece protobuf "datasets==4.3.0" "huggingface_hub>=0.34.0" hf_transfer
#     !pip install --no-deps unsloth
# !pip install transformers==4.56.2
# !pip install --no-deps trl==0.22.2

from unsloth import FastLanguageModel
import torch
max_seq_length = 2048 # Choose any! We auto support RoPE Scaling internally!
dtype = None # None for auto detection. Float16 for Tesla T4, V100, Bfloat16 for Ampere+
load_in_4bit = True # Use 4bit quantization to reduce memory usage. Can be False.

fourbit_models = [
    "unsloth/Meta-Llama-3.1-8B-bnb-4bit",      # Llama-3.1 15 trillion tokens model 2x faster!
    "unsloth/Meta-Llama-3.1-8B-Instruct-bnb-4bit",
    "unsloth/Meta-Llama-3.1-70B-bnb-4bit",
    "unsloth/Meta-Llama-3.1-405B-bnb-4bit",    # We also uploaded 4bit for 405b!
    "unsloth/Mistral-Nemo-Base-2407-bnb-4bit", # New Mistral 12b 2x faster!
    "unsloth/Mistral-Nemo-Instruct-2407-bnb-4bit",
    "unsloth/mistral-7b-v0.3-bnb-4bit",        # Mistral v3 2x faster!
    "unsloth/mistral-7b-instruct-v0.3-bnb-4bit",
    "unsloth/Phi-3.5-mini-instruct",           # Phi-3.5 2x faster!
    "unsloth/Phi-3-medium-4k-instruct",
    "unsloth/gemma-2-9b-bnb-4bit",
    "unsloth/gemma-2-27b-bnb-4bit",            # Gemma 2x faster!
]

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/Meta-Llama-3.1-8B",
    max_seq_length = max_seq_length,
    dtype = dtype,
    load_in_4bit = load_in_4bit,
    # token = "hf_...", # use one if using gated models like meta-llama/Llama-2-7b-hf
)

model = FastLanguageModel.get_peft_model(
    model,
    r = 64, # Choose any number > 0 ! Suggested 8, 16, 32, 64, 128
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                      "gate_proj", "up_proj", "down_proj",],
    lora_alpha = 16,
    lora_dropout = 0, # Supports any, but = 0 is optimized
    bias = "none",    # Supports any, but = "none" is optimized
    use_gradient_checkpointing = "unsloth", # True or "unsloth" for very long context
    random_state = 3407,
    use_rslora = False,  # We support rank stabilized LoRA
    loftq_config = None, # And LoftQ
)

from trl import SFTConfig, SFTTrainer
from datasets import Dataset


dataset = Dataset.from_list(result)

alpaca_prompt = """Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### Instruction:
{}

### Input:
{}

### Response:
{}"""

EOS_TOKEN = tokenizer.eos_token # Must add EOS_TOKEN

def formatting_prompts_func(examples):
    instructions = examples["instruction"]
    inputs       = examples["input"]
    outputs      = examples["output"]
    texts = []
    for instruction, input, output in zip(instructions, inputs, outputs):
        # Must add EOS_TOKEN, otherwise generation will go on forever!
        text = alpaca_prompt.format(instruction, input, output) + EOS_TOKEN
        texts.append(text)
    return { "text" : texts, }

dataset = dataset.map(formatting_prompts_func, batched = True)

trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    dataset_text_field = "text",
    max_seq_length = max_seq_length,
    packing = False, # Can make training 5x faster for short sequences.
    args = SFTConfig(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 5,
        # num_train_epochs = 1, # Set this for 1 full training run.
        max_steps = 60,
        learning_rate = 2e-4,
        logging_steps = 1,
        optim = "adamw_8bit",
        weight_decay = 0.001,
        lr_scheduler_type = "linear",
        seed = 3407,
        output_dir = "outputs",
        report_to = "none", # Use TrackIO/WandB etc
    ),
)

gpu_stats = torch.cuda.get_device_properties(0)
start_gpu_memory = round(torch.cuda.max_memory_reserved() / 1024 / 1024 / 1024, 3)
max_memory = round(gpu_stats.total_memory / 1024 / 1024 / 1024, 3)
print(f"GPU = {gpu_stats.name}. Max memory = {max_memory} GB.")
print(f"{start_gpu_memory} GB of memory reserved.")

trainer_stats = trainer.train()

used_memory = round(torch.cuda.max_memory_reserved() / 1024 / 1024 / 1024, 3)
used_memory_for_lora = round(used_memory - start_gpu_memory, 3)
used_percentage = round(used_memory / max_memory * 100, 3)
lora_percentage = round(used_memory_for_lora / max_memory * 100, 3)
print(f"{trainer_stats.metrics['train_runtime']} seconds used for training.")
print(
    f"{round(trainer_stats.metrics['train_runtime']/60, 2)} minutes used for training."
)
print(f"Peak reserved memory = {used_memory} GB.")
print(f"Peak reserved memory for training = {used_memory_for_lora} GB.")
print(f"Peak reserved memory % of max memory = {used_percentage} %.")
print(f"Peak reserved memory for training % of max memory = {lora_percentage} %.")

FastLanguageModel.for_inference(model)
inputs = tokenizer(
[
    alpaca_prompt.format(
        "Generate a high-conviction romantic line..", # instruction
        "Target: Into [X: Destiny] and loves [Y: Life Stories].", # input
        "",
    )
], return_tensors = "pt").to("cuda")

outputs = model.generate(**inputs, max_new_tokens = 64, use_cache = True)
tokenizer.batch_decode(outputs)

full_text = tokenizer.batch_decode(outputs)[0]

clean_response = full_text.split("### Response:\n")[-1].replace("<|end_of_text|>", "").strip()

print("Generated Line:")
print(clean_response)

